micronaut:
  application:
    name: analysis-result
  server:
    port: 80
    cors:
      enabled: true
      configurations:
        web:
          allowedMethods:
            - POST
            - PUT
            - GET
  http.client.read-timeout: 60
mongodb:
  servers:
    osmolytics:
      dbname: inventory
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
